import {Filter} from "./models";

export const jobType: Filter[] = [
  {name:"Full Time", category:"jobType", query:"full-time"},
  {name:"Part Time", category:"jobType", query:"part-time"},
  {name:"Internship / Voluntariat", category:"jobType", query:"internship,voluntariat"},
  {name:"Proiect / Sezonier", category:"jobType", query:"proiect,sezonier"}
]

export const studyLevel: Filter[] = [
  {name:"Necalificat", category:"study_level", query:"necalificat"},
  {name:"Calificat", category:"study_level", query:"calificat"},
  {name:"Student", category:"study_level", query:"student"},
  {name:"Absolvent", category:"study_level", query:"absolvent"},
]

export const experienceLevel: Filter[] = [
  {name:"Fara experienta", category:"experience_level", query:"fara-experienta"},
  {name:"Entry Level (< 2 ani)", category:"experience_level", query:"entry-level"},
  {name:"Senior level(> 5 ani)", category:"experience_level", query:"senior"},
  {name:"Manager / Executiv", category:"experience_level", query:"manager"}

]

export const cities: Filter[] = [
  {name: "Abrud", category: "location", query: "Abrud"},
  {name: "Adjud", category: "location", query: "Adjud"},
  {name: "Agnita", category: "location", query: "Agnita"},
  {name: "Aiud", category: "location", query: "Aiud"},
  {name: "Alba Iulia", category: "location", query: "Alba%20Iulia"},
  {name: "Aleșd", category: "location", query: "Alesd"},
  {name: "Alexandria", category: "location", query: "Alexandria"},
  {name: "Amara", category: "location", query: "Amara"},
  {name: "Anina", category: "location", query: "Anina"},
  {name: "Aninoasa", category: "location", query: "Aninoasa"},
  {name: "Arad", category: "location", query: "Arad"},
  {name: "Ardud", category: "location", query: "Ardud"},
  {name: "Avrig", category: "location", query: "Avrig"},
  {name: "Azuga", category: "location", query: "Azuga"},
  {name: "Babadag", category: "location", query: "Babadag"},
  {name: "Băbeni", category: "location", query: "Babeni"},
  {name: "Bacău", category: "location", query: "Bacau"},
  {name: "Baia de Aramă", category: "location", query: "Baia%20de%20Arama"},
  {name: "Baia de Arieș", category: "location", query: "Baia%20de%20Aries"},
  {name: "Baia Mare", category: "location", query: "Baia%20Mare"},
  {name: "Baia Sprie", category: "location", query: "Baia%20Sprie"},
  {name: "Băicoi", category: "location", query: "Baicoi"},
  {name: "Băile Govora", category: "location", query: "Baile%20Govora"},
  {name: "Băile Herculane", category: "location", query: "Baile%20Herculane"},
  {name: "Băile Olănești", category: "location", query: "Baile%20Olanesti"},
  {name: "Băile Tușnad", category: "location", query: "Baile%20Tusnad"},
  {name: "Băilești", category: "location", query: "Bailesti"},
  {name: "Bălan", category: "location", query: "Balan"},
  {name: "Bălcești", category: "location", query: "Balcesti"},
  {name: "Balș", category: "location", query: "Bals"},
  {name: "Baraolt", category: "location", query: "Baraolt"},
  {name: "Bârlad", category: "location", query: "Barlad"},
  {name: "Bechet", category: "location", query: "Bechet"},
  {name: "Beclean", category: "location", query: "Beclean"},
  {name: "Beiuș", category: "location", query: "Beius"},
  {name: "Berbești", category: "location", query: "Berbesti"},
  {name: "Berești", category: "location", query: "Beresti"},
  {name: "Bicaz", category: "location", query: "Bicaz"},
  {name: "Bistrița", category: "location", query: "Bistrita"},
  {name: "Blaj", category: "location", query: "Blaj"},
  {name: "Bocșa", category: "location", query: "Bocsa"},
  {name: "Boldești-Scăeni", category: "location", query: "Boldesti-Scaeni"},
  {name: "Bolintin-Vale", category: "location", query: "Bolintin-Vale"},
  {name: "Borșa", category: "location", query: "Borsa"},
  {name: "Borsec", category: "location", query: "Borsec"},
  {name: "Botoșani", category: "location", query: "Botosani"},
  {name: "Brad", category: "location", query: "Brad"},
  {name: "Bragadiru", category: "location", query: "Bragadiru"},
  {name: "Brăila", category: "location", query: "Braila"},
  {name: "Brașov", category: "location", query: "Brasov"},
  {name: "Breaza", category: "location", query: "Breaza"},
  {name: "Brezoi", category: "location", query: "Brezoi"},
  {name: "Broșteni", category: "location", query: "Brosteni"},
  {name: "Bucecea", category: "location", query: "Bucecea"},
  {name: "București", category: "location", query: "Bucuresti"},
  {name: "Budești", category: "location", query: "Budesti"},
  {name: "Buftea", category: "location", query: "Buftea"},
  {name: "Buhuși", category: "location", query: "Buhusi"},
  {name: "Bumbești-Jiu", category: "location", query: "Bumbesti-Jiu"},
  {name: "Bușteni", category: "location", query: "Busteni"},
  {name: "Buzău", category: "location", query: "Buzau"},
  {name: "Buziaș", category: "location", query: "Buzias"},
  {name: "Cajvana", category: "location", query: "Cajvana"},
  {name: "Calafat", category: "location", query: "Calafat"},
  {name: "Călan", category: "location", query: "Calan"},
  {name: "Călărași", category: "location", query: "Calarasi"},
  {name: "Călimănești", category: "location", query: "Calimanesti"},
  {name: "Câmpeni", category: "location", query: "Campeni"},
  {name: "Câmpia Turzii", category: "location", query: "Campia%20Turzii"},
  {name: "Câmpina", category: "location", query: "Campina"},
  {name: "Câmpulung Moldovenesc", category: "location", query: "Campulung%20Moldovenesc"},
  {name: "Câmpulung", category: "location", query: "Campulung"},
  {name: "Caracal", category: "location", query: "Caracal"},
  {name: "Caransebeș", category: "location", query: "Caransebes"},
  {name: "Carei", category: "location", query: "Carei"},
  {name: "Cavnic", category: "location", query: "Cavnic"},
  {name: "Căzănești", category: "location", query: "Cazanesti"},
  {name: "Cehu Silvaniei", category: "location", query: "Cehu%20Silvaniei"},
  {name: "Cernavodă", category: "location", query: "Cernavoda"},
  {name: "Chișineu-Criș", category: "location", query: "Chisineu-Cris"},
  {name: "Chitila", category: "location", query: "Chitila"},
  {name: "Ciacova", category: "location", query: "Ciacova"},
  {name: "Cisnădie", category: "location", query: "Cisnadie"},
  {name: "Cluj-Napoca", category: "location", query: "Cluj-Napoca"},
  {name: "Codlea", category: "location", query: "Codlea"},
  {name: "Comănești", category: "location", query: "Comanesti"},
  {name: "Comarnic", category: "location", query: "Comarnic"},
  {name: "Constanța", category: "location", query: "Constanta"},
  {name: "Copșa Mică", category: "location", query: "Copsa%20Mica"},
  {name: "Corabia", category: "location", query: "Corabia"},
  {name: "Costești", category: "location", query: "Costesti"},
  {name: "Covasna", category: "location", query: "Covasna"},
  {name: "Craiova", category: "location", query: "Craiova"},
  {name: "Cristuru Secuiesc", category: "location", query: "Cristuru%20Secuiesc"},
  {name: "Cugir", category: "location", query: "Cugir"},
  {name: "Curtea de Argeș", category: "location", query: "Curtea%20de%20Arges"},
  {name: "Curtici", category: "location", query: "Curtici"},
  {name: "Dăbuleni", category: "location", query: "Dabuleni"},
  {name: "Darabani", category: "location", query: "Darabani"},
  {name: "Dărmănești", category: "location", query: "Darmanesti"},
  {name: "Dej", category: "location", query: "Dej"},
  {name: "Deta", category: "location", query: "Deta"},
  {name: "Deva", category: "location", query: "Deva"},
  {name: "Dolhasca", category: "location", query: "Dolhasca"},
  {name: "Dorohoi", category: "location", query: "Dorohoi"},
  {name: "Drăgănești-Olt", category: "location", query: "Draganesti-Olt"},
  {name: "Drăgășani", category: "location", query: "Dragasani"},
  {name: "Dragomirești", category: "location", query: "Dragomiresti"},
  {name: "Drobeta-Turnu Severin", category: "location", query: "Drobeta-Turnu%20Severin"},
  {name: "Dumbrăveni", category: "location", query: "Dumbraveni"},
  {name: "Eforie", category: "location", query: "Eforie"},
  {name: "Făgăraș", category: "location", query: "Fagaras"},
  {name: "Făget", category: "location", query: "Faget"},
  {name: "Fălticeni", category: "location", query: "Falticeni"},
  {name: "Făurei", category: "location", query: "Faurei"},
  {name: "Fetești", category: "location", query: "Fatesti"},
  {name: "Fieni", category: "location", query: "Fieni"},
  {name: "Fierbinți-Târg", category: "location", query: "Fierbinti-Targ"},
  {name: "Filiași", category: "location", query: "Filiasi"},
  {name: "Flămânzi", category: "location", query: "Flamanzi"},
  {name: "Focșani", category: "location", query: "Focsani"},
  {name: "Frasin", category: "location", query: "Frasin"},
  {name: "Fundulea", category: "location", query: "Fundulea"},
  {name: "Găești", category: "location", query: "Gaesti"},
  {name: "Galați", category: "location", query: "Galati"},
  {name: "Gătaia", category: "location", query: "Gataia"},
  {name: "Geoagiu", category: "location", query: "Geoagiu"},
  {name: "Gheorgheni", category: "location", query: "Gheorgheni"},
  {name: "Gherla", category: "location", query: "Gherla"},
  {name: "Ghimbav", category: "location", query: "Ghimbav"},
  {name: "Giurgiu", category: "location", query: "Giurgiu"},
  {name: "Gura Humorului", category: "location", query: "Gura%20Humorului"},
  {name: "Hârlău", category: "location", query: "Harlau"},
  {name: "Hârșova", category: "location", query: "Harsova"},
  {name: "Hațeg", category: "location", query: "Hateg"},
  {name: "Horezu", category: "location", query: "Horezu"},
  {name: "Huedin", category: "location", query: "Huedin"},
  {name: "Hunedoara", category: "location", query: "Hunedoara"},
  {name: "Huși", category: "location", query: "Husi"},
  {name: "Ianca", category: "location", query: "Ianca"},
  {name: "Iași", category: "location", query: "Iasi"},
  {name: "Iernut", category: "location", query: "Iernut"},
  {name: "Ineu", category: "location", query: "Ineu"},
  {name: "Însurăței", category: "location", query: "Insuratei"},
  {name: "Întorsura Buzăului", category: "location", query: "Intorsura%20Buzăului"},
  {name: "Isaccea", category: "location", query: "Isaccea"},
  {name: "Jibou", category: "location", query: "Jibou"},
  {name: "Jimbolia", category: "location", query: "Jimbolia"},
  {name: "Lehliu Gară", category: "location", query: "Lehliu%20Gara"},
  {name: "Lipova", category: "location", query: "Lipova"},
  {name: "Liteni", category: "location", query: "Liteni"},
  {name: "Livada", category: "location", query: "Livada"},
  {name: "Luduș", category: "location", query: "Ludus"},
  {name: "Lugoj", category: "location", query: "Lugoj"},
  {name: "Lupeni", category: "location", query: "Lupeni"},
  {name: "Măcin", category: "location", query: "Macin"},
  {name: "Măgurele", category: "location", query: "Magurele"},
  {name: "Mangalia", category: "location", query: "Mangalia"},
  {name: "Mărășești", category: "location", query: "Marasesti"},
  {name: "Marghita", category: "location", query: "Marghita"},
  {name: "Medgidia", category: "location", query: "Medgidia"},
  {name: "Mediaș", category: "location", query: "Medias"},
  {name: "Miercurea Ciuc", category: "location", query: "Miercurea%20Ciuc"},
  {name: "Miercurea Nirajului", category: "location", query: "Miercurea%20Nirajului"},
  {name: "Miercurea Sibiului", category: "location", query: "Miercurea%20Sibiului"},
  {name: "Mihăilești", category: "location", query: "Mihailești"},
  {name: "Milișăuți", category: "location", query: "Milisauti"},
  {name: "Mioveni", category: "location", query: "Mioveni"},
  {name: "Mizil", category: "location", query: "Mizil"},
  {name: "Moinești", category: "location", query: "Moinesti"},
  {name: "Moldova Nouă", category: "location", query: "Moldova%20Noua"},
  {name: "Moreni", category: "location", query: "Moreni"},
  {name: "Motru", category: "location", query: "Motru"},
  {name: "Murfatlar", category: "location", query: "Murfatlar"},
  {name: "Murgeni", category: "location", query: "Murgeni"},
  {name: "Nădlac", category: "location", query: "Nadlac"},
  {name: "Năsăud", category: "location", query: "Nasaud"},
  {name: "Năvodari", category: "location", query: "Navodari"},
  {name: "Negrești", category: "location", query: "Negresti"},
  {name: "Negrești-Oaș", category: "location", query: "Negresti-Oas"},
  {name: "Negru Vodă", category: "location", query: "Negru%20Voda"},
  {name: "Nehoiu", category: "location", query: "Nehoiu"},
  {name: "Novaci", category: "location", query: "Novaci"},
  {name: "Nucet", category: "location", query: "Nucet"},
  {name: "Ocna Mureș", category: "location", query: "Ocna%20Mures"},
  {name: "Ocna Sibiului", category: "location", query: "Ocna%20Sibiului"},
  {name: "Ocnele Mari", category: "location", query: "Ocnele%20Mari"},
  {name: "Odobești", category: "location", query: "Odobesti"},
  {name: "Odorheiu Secuiesc", category: "location", query: "Odorheiu%20Secuiesc"},
  {name: "Oltenița", category: "location", query: "Oltenita"},
  {name: "Onești", category: "location", query: "Onesti"},
  {name: "Oradea", category: "location", query: "Oradea"},
  {name: "Orăștie", category: "location", query: "Orastie"},
  {name: "Oravița", category: "location", query: "Oravita"},
  {name: "Orșova", category: "location", query: "Orsova"},
  {name: "Oțelu Roșu", category: "location", query: "Oțelu%20Rosu"},
  {name: "Otopeni", category: "location", query: "Otopeni"},
  {name: "Ovidiu", category: "location", query: "Ovidiu"},
  {name: "Panciu", category: "location", query: "Panciu"},
  {name: "Pâncota", category: "location", query: "Pancota"},
  {name: "Pantelimon", category: "location", query: "Pantelimon"},
  {name: "Pașcani", category: "location", query: "Pascani"},
  {name: "Pătârlagele", category: "location", query: "Patarlagele"},
  {name: "Pecica", category: "location", query: "Pecica"},
  {name: "Petrila", category: "location", query: "Petrila"},
  {name: "Petroșani", category: "location", query: "Petrosani"},
  {name: "Piatra Neamț", category: "location", query: "Piatra%20Neamt"},
  {name: "Piatra-Olt", category: "location", query: "Piatra-Olt"},
  {name: "Pitești", category: "location", query: "Pitesti"},
  {name: "Ploiești", category: "location", query: "Ploiesti"},
  {name: "Plopeni", category: "location", query: "Plopeni"},
  {name: "Podu Iloaiei", category: "location", query: "Podu%20Iloaiei"},
  {name: "Pogoanele", category: "location", query: "Pogoanele"},
  {name: "Popești-Leordeni", category: "location", query: "Popesti-Leordeni"},
  {name: "Potcoava", category: "location", query: "Potcoava"},
  {name: "Predeal", category: "location", query: "Predeal"},
  {name: "Pucioasa", category: "location", query: "Pucioasa"},
  {name: "Răcari", category: "location", query: "Racari"},
  {name: "Rădăuți", category: "location", query: "Radauti"},
  {name: "Râmnicu Sărat", category: "location", query: "Ramnicu%20Sarat"},
  {name: "Râmnicu Vâlcea", category: "location", query: "Ramnicu%20Valcea"},
  {name: "Râșnov", category: "location", query: "Rasnov"},
  {name: "Recaș", category: "location", query: "Recas"},
  {name: "Reghin", category: "location", query: "Reghin"},
  {name: "Reșița", category: "location", query: "Resita"},
  {name: "Roman", category: "location", query: "Roman"},
  {name: "Roșiorii de Vede", category: "location", query: "Rosiorii%20de%20Vede"},
  {name: "Rovinari", category: "location", query: "Rovinari"},
  {name: "Roznov", category: "location", query: "Roznov"},
  {name: "Rupea", category: "location", query: "Rupea"},
  {name: "Săcele", category: "location", query: "Sacele"},
  {name: "Săcueni", category: "location", query: "Sacieni"},
  {name: "Salcea", category: "location", query: "Salcea"},
  {name: "Săliște", category: "location", query: "Saliste"},
  {name: "Săliștea de Sus", category: "location", query: "Salistea%20de%20Sus"},
  {name: "Salonta", category: "location", query: "Salonta"},
  {name: "Sângeorgiu de Pădure", category: "location", query: "Sangeorgiu%20de%20Padure"},
  {name: "Sângeorz-Băi", category: "location", query: "Sangeorz-Bai"},
  {name: "Sânnicolau Mare", category: "location", query: "Sannicolau%20Mare"},
  {name: "Sântana", category: "location", query: "Santana"},
  {name: "Sărmașu", category: "location", query: "Sarmasu"},
  {name: "Satu Mare", category: "location", query: "Satu%20Mare"},
  {name: "Săveni", category: "location", query: "Saveni"},
  {name: "Scornicești", category: "location", query: "Scornicesti"},
  {name: "Sebeș", category: "location", query: "Sebes"},
  {name: "Sebiș", category: "location", query: "Sebis"},
  {name: "Segarcea", category: "location", query: "Segarcea"},
  {name: "Seini", category: "location", query: "Seini"},
  {name: "Sfântu Gheorghe", category: "location", query: "Sfantu%20Gheorghe"},
  {name: "Sibiu", category: "location", query: "Sibiu"},
  {name: "Sighetu Marmației", category: "location", query: "Sighetu%20Marmatiei"},
  {name: "Sighișoara", category: "location", query: "Sighisoara"},
  {name: "Simeria", category: "location", query: "Simeria"},
  {name: "Șimleu Silvaniei", category: "location", query: "Simleu%20Silvaniei"},
  {name: "Sinaia", category: "location", query: "Sinaia"},
  {name: "Siret", category: "location", query: "Siret"},
  {name: "Slănic", category: "location", query: "Slanic"},
  {name: "Slănic-Moldova", category: "location", query: "Slanic-Moldova"},
  {name: "Slatina", category: "location", query: "Slatina"},
  {name: "Slobozia", category: "location", query: "Slobozia"},
  {name: "Solca", category: "location", query: "Solca"},
  {name: "Șomcuta Mare", category: "location", query: "Somcuta%20Mare"},
  {name: "Sovata", category: "location", query: "Sovata"},
  {name: "Ștefănești, Argeș", category: "location", query: "Stefanesti,%20Arges"},
  {name: "Ștefănești, Botoșani", category: "location", query: "Stefanesti,%20Botosani"},
  {name: "Ștei", category: "location", query: "Stei"},
  {name: "Strehaia", category: "location", query: "Strehaia"},
  {name: "Suceava", category: "location", query: "Suceava"},
  {name: "Sulina", category: "location", query: "Sulina"},
  {name: "Tălmaciu", category: "location", query: "Talmaciu"},
  {name: "Țăndărei", category: "location", query: "Tandarei"},
  {name: "Târgoviște", category: "location", query: "Targoviste"},
  {name: "Târgu Bujor", category: "location", query: "Targu%20Bujor"},
  {name: "Târgu Cărbunești", category: "location", query: "Targu%20Carbunesti"},
  {name: "Târgu Frumos", category: "location", query: "Targu%20Frumos"},
  {name: "Târgu Jiu", category: "location", query: "Targu%20Jiu"},
  {name: "Târgu Lăpuș", category: "location", query: "Targu%20Lapus"},
  {name: "Târgu Mureș", category: "location", query: "Targu%20Mures"},
  {name: "Târgu Neamț", category: "location", query: "Targu%20Neamt"},
  {name: "Târgu Ocna", category: "location", query: "Targu%20Ocna"},
  {name: "Târgu Secuiesc", category: "location", query: "Targu%20Secuiesc"},
  {name: "Târnăveni", category: "location", query: "Tarnaveni"},
  {name: "Tășnad", category: "location", query: "Tasnad"},
  {name: "Tăuții-Măgherăuș", category: "location", query: "Tautii-Magheraus"},
  {name: "Techirghiol", category: "location", query: "Techirghiol"},
  {name: "Tecuci", category: "location", query: "Tecuci"},
  {name: "Teiuș", category: "location", query: "Teius"},
  {name: "Țicleni", category: "location", query: "Ticleni"},
  {name: "Timișoara", category: "location", query: "Timisoara"},
  {name: "Tismana", category: "location", query: "Tismana"},
  {name: "Titu", category: "location", query: "Titu"},
  {name: "Toplița", category: "location", query: "Toplita"},
  {name: "Topoloveni", category: "location", query: "Topoloveni"},
  {name: "Tulcea", category: "location", query: "Tulcea"},
  {name: "Turceni", category: "location", query: "Turceni"},
  {name: "Turda", category: "location", query: "Turda"},
  {name: "Turnu Măgurele", category: "location", query: "Turnu%20Magurele"},
  {name: "Ulmeni", category: "location", query: "Ulmeni"},
  {name: "Ungheni", category: "location", query: "Ungheni"},
  {name: "Uricani", category: "location", query: "Uricani"},
  {name: "Urlați", category: "location", query: "Urlati"},
  {name: "Urziceni", category: "location", query: "Urziceni"},
  {name: "Valea lui Mihai", category: "location", query: "Valea%20lui%20Mihai"},
  {name: "Vălenii de Munte", category: "location", query: "Valenii%20de%20Munte"},
  {name: "Vânju Mare", category: "location", query: "Vanju%20Mare"},
  {name: "Vașcău", category: "location", query: "Vascau"},
  {name: "Vaslui", category: "location", query: "Vaslui"},
  {name: "Vatra Dornei", category: "location", query: "Vatra%20Dornei"},
  {name: "Vicovu de Sus", category: "location", query: "Vicovu%20de%20Sus"},
  {name: "Victoria", category: "location", query: "Victoria"},
  {name: "Videle", category: "location", query: "Videle"},
  {name: "Vișeu de Sus", category: "location", query: "Viseu%20de%20Sus"},
  {name: "Vlăhița", category: "location", query: "Vlahita"},
  {name: "Voluntari", category: "location", query: "Voluntari"},
  {name: "Vulcan", category: "location", query: "Vulcan"},
  {name: "Zalău", category: "location", query: "Zalau"},
  {name: "Zărnești", category: "location", query: "Zarnesti"},
  {name: "Zimnicea", category: "location", query: "Zimnicea"},
  {name: "Zlatna", category: "location", query: "Zlatna"}
];
